### ISSUE TITLE
Watson tone analyzer is not working

### ISSUE THREAD

**Issue by GRMK11** [lissy93/twitter-sentiment-visualisation#33]
Hi 
Watson tone analyzer is not working , even when I entered  new credentials  , it is saying invalid credentials.Can you throw me some light on this?
Thanks in advance,
Manohar
 also How to proceed further , for the below king of warning
WARNING: This method of instantiating the Watson services has been deprecated beginning with Version 3.0.0 of the Node SDK.  Please refer to the Node SDK documentation for information on how t
o instantiate Watson services.  This form of service instantiation  will be removed in a future release of the SDK.

**Comment by lissy93** [comment]
Hi @GRMK11 
So the older SDK is now deprecated by IBM, (see their [change log](https://github.com/watson-developer-cloud/node-sdk/wiki/Change-Log)). But they have now got an official Node package (which they didn't have when I wrote app, hence I have to integrate with the API's manually). So I would recommend that you use that instead, check it out here: [github.com/watson-developer-cloud/node-sdk](https://github.com/watson-developer-cloud/node-sdk/).

Thanks for raising this, when I get a moment, I will update this repo to either work with the latest SDK, or integrate the official package into it. Alternatively the tone analyser feature may just have to be removed (since their free-tier limits are much lower now, and my live site get a lot a lot of traffic). Pull requests are always welcome if you'd like to make the update.

Feel free to comment, or re-open the issue if you have any more trouble with this,

Cheers,
Alicia :rocket:

**Comment by GRMK11** [comment]
Hey thanks for your prompt response , I will try that and will let you know the status.
Thanks, 
Manohar
